# PBS configuration
queue: normal
project: e14
walltime: 5:00:00
jobname: 01deg_jra55_ryf
ncpus: 7216

shortpath: /short/e14

# Model configuration
model: access-om2
submodels:
    - name: atmosphere
      model: matm
      exe: matm_jra55_77ca58ce.exe
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_55a1bd92.x
      input: mom_01deg
      timestep: 450
      ncpus: 6000

    - name: ice
      model: cice5
      exe: cice_auscom_3600x2700_1200p_fb3693fe.exe
      input: cice_01deg
      timestep: 450
      ncpus: 1200

    - name: coupler
      model: oasis
      input: oasis_jra55_to_01deg
      timestep: 450
      ncpus: 0

calendar:
    runtime:
        years: 0
        months: 3
        days: 0

    start:
        year: 1
        month: 1
        days: 1

# Collation
collate: true
collate_walltime: 10:00:00
collate_mem: 64GB
collate_ncpus: 4
collate_queue: express
collate_flags: -n4 -z -m -r

# Misc
runlog: False
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 --mca btl_openib_eager_limit 4096 --mca btl_openib_max_send_size 8192 --mca mtl mxm
qsub_flags: -lother=hyperthread
ipm: 2.0.5


