# PBS configuration
queue: normal
project: e14
walltime: 5:00:00
jobname: 025deg_jra55_ryf
ncpus: 2416

shortpath: /short/e14

# Model configuration
model: access-om2
submodels:
    - name: atmosphere
      model: matm
      exe: matm_jra55_77ca58ce.exe
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_55a1bd92.x
      input: mom_025deg
      timestep: 400
      ncpus: 1920

    - name: ice
      model: cice5
      exe: cice_auscom_1440x1080_480p_fb3693fe.exe
      input: cice_025deg
      timestep: 400
      ncpus: 480

    - name: coupler
      model: oasis
      input: oasis_jra55_to_025deg
      timestep: 400
      ncpus: 0

calendar:
    runtime:
        years: 0
        months: 6
        days: 0

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 4
collate_flags: -n4 -z -m -r
collate_mem: 30GB
mpirun: --mca orte_base_help_aggregate 0 --mca btl_openib_eager_limit 4096 --mca btl_openib_max_send_size 8192 --mca mtl mxm
qsub_flags: -lother=hyperthread -W umask=027
