# PBS configuration
queue: express
project: e14
walltime: 5:00:00
jobname: 1deg_jra55_ryf
ncpus: 256

shortpath: /short/e14

# Model configuration
model: access-om2
submodels:
    - name: atmosphere
      model: matm
      exe: matm_jra55_7213855e.exe
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_cd0deba3.x
      input: mom_1deg
      timestep: 1800
      ncpus: 216

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p_fa5b0bcf.exe
      input: cice_1deg
      timestep: 1800
      ncpus: 24

    - name: coupler
      model: oasis
      input: oasis_jra55_to_1deg
      timestep: 1800
      ncpus: 0


calendar:
    runtime:
        years: 2
        months: 0
        days: 0

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread
